### ISSUE TITLE
Something weird with Efab tanks

### ISSUE THREAD

**Issue by 016Nojr** [McJty/EFab#1]
Something weird is happening with Efab tanks on the Continuum test server.

The multiblock consists of the crafting grid, a tank with 800mb lava on the east side of the crafting grid and a gear box on the south side of the crafting grid.

Steps I did to cause the crash:
1. Place another tank on top of the lava tank
2. Break the tank
3. Place it on top of the crafting grid
4. Break the tank
5. Place it on the west side of the crafting grid, [Crashlog](https://gist.github.com/016Nojr/f3add55f9b86817e6a47c42a33b3eec7)
6. Relaunched, tank is still in inventory.
7. Try placing it again, same crash.
8. Relaunched, tank is now placed, and I have a tank in my inventory. Duped the tank
9. Place the tank south of the gear box, same crash.
10. Place the tank without connection to the multiblock, same crash.
11. Place the tank on the same block as step 10, same crash, no dupe

**Comment by McJty** [comment]
Fixed in next update. Thanks for the detailed description
