### ISSUE TITLE
Multiple Efab Crafting Grids on one system cause severe TPS issues

### ISSUE THREAD

**Issue by Cyphecx** [McJty/EFab#10]
I beleive that this issue is known, but using Tick Profiler I got some data regarding the effects of additional Efab grids on tps

With the 5 Grid setup I was running:
                   Average Time/tick      
grid.GridTE  25.039

Overworld TPS: 2.9333

After removing all but one grid:
                   Average Time/tick
grid.GridTE: no longer listed(negligable)

Overworld tps: 19.96

The server was operating perfectly even with many grids for a while, but seemingly spontaneously, they started creating severe TPS issues.

**Comment by McJty** [comment]
This should no longer be the case with the latest efab

**Comment by Cyphecx** [comment]
I am playing on Continuum version 1.10 its possible that it does not have the newest version of efab
