### ISSUE TITLE
[Continuum] ME Controller doesn't craft instantly with Power Optimizer

### ISSUE THREAD

**Issue by aaronhowser1** [McJty/EFab#11]
FTBTeam/FTB-Continuum/issues/180

![](https://user-images.githubusercontent.com/15698722/41195824-54da0b3e-6bfa-11e8-8818-1c53d3a2286b.png)

This EFab has a Power Optimizer, but it doesn't craft the ME Controller instantly. 

This is the recipe:
![image](https://user-images.githubusercontent.com/15698722/41195920-e3eae93c-6bfb-11e8-9802-10e07d515ccb.png)

This is what it looks like in efab_recipes.cfg:

  {
    "type": "shaped",
    "output": {
      "item": "appliedenergistics2:controller"
```
    },
    "input": [
      "aba",
      "bcb",
      "aba"
    ],
    "inputmap": {
	  "a": {
        "item": "actuallyadditions:block_crystal_empowered",
		"meta": 1
      },
	  "b": {
        "item": "techreborn:part",
		"meta": 3
      },
	  "c": "netherStar"
    },
    "time": 18000,
    "tiers": [
      "GEARBOX",
      "RF",
	  "UPGRADE_DIGITAL",
	  "UPGRADE_POWER"
    ],
    "rfpertick": 2000
  },

```

**Comment by McJty** [comment]
Fixed for next release
