### ISSUE TITLE
Advanced RF Storages provide no RF/t to the EFab 

### ISSUE THREAD

**Issue by aaronhowser1** [McJty/EFab#12]
Advanced RF Storages provide no RF/t to the EFab. This multiblock should be providing 1050 RF/t , but it only provides 50.

![image](https://user-images.githubusercontent.com/15698722/41196362-ccb256b2-6c03-11e8-86ca-498e9e07f60a.png)

This is using efab-0.0.37.jar

FTBTeam/FTB-Continuum/issues/181

**Comment by McJty** [comment]
What configs is Continuum using for the advanced RF storage?

**Comment by aaronhowser1** [comment]
```
    # How much RF/t the advanced RF Storage block can contribute to crafting [range: 1 ~ 1000000, default: 100]
    I:advancedRfStorageInternalFlow=1000

    # The maximum amount of RF for the advanced RF Storage block [range: 1 ~ 10000000, default: 100000]
    I:advancedRfStorageMax=1000000

```

**Comment by Ravalli03** [comment]
Having same issue, can't craft any advanced items due to not enough r/f. I don't get error but as soon as I start the craft it stops.

**Comment by McJty** [comment]
Fixed next release. Was a stupid bug
