### ISSUE TITLE
Advanced RF Storage Only Providing the Power of a Regular RF Storage

### ISSUE THREAD

**Issue by droidix** [McJty/EFab#15]
Advanced RF Storage blocks are only providing the power of regular RF Storage blocks during the crafting operation.  For example, in Continuum, the ME Controller requires 2,000 RF/t, but the crafting operation immediately stops after clicking start and the EFab monitor flashes "error".   This is when using two Advanced RF Storage blocks (configured at 1,000 RF/t each).  However, eight regular RF Storage blocks work fine (configured at 250 RF/t each).

The resolution of issue #12 fixed the initial error before you could even begin the crafting operation.  This new issue appears to be caused by this line:

https://github.com/McJtyMods/EFab/blob/d451343a7c27f6b7267fa28bb0e271bac1e37449/src/main/java/mcjty/efab/blocks/grid/GridTE.java#L400

Each RF Storage is being capped at the configured value of a regular RF Storage instead of determining the type of RF Storage and using its configured amount.

Mod version: efab-0.1.0

**Comment by lurch9229** [comment]
I have a similar issue where the efab doesn't even recognise the advanced rf storage, therefore 1000rf/t for dragging just by making an advanced block, any work rounds other than putting them aside and making more tier 1 storge

**Comment by McJty** [comment]
I will try to check this out soon

**Comment by McJty** [comment]
Fixed next release
