### ISSUE TITLE
Idea: Autocrafting Upgrades

### ISSUE THREAD

**Issue by Chaftalie** [McJty/EFab#16]
At the moment I am playing continuum and I could not find a way (Even after googling it) of autocrafting things that use upgrades like the power or the digital upgrade.

If there is a way I am sorry for spamming your github messages, if not i would suggest an **endgame** solution for this problem. 
Because it is realy annoying to craft thousands of stack manually, even if you use more then 1 crafting Grid.

**Comment by McJty** [comment]
Just make sure all your crafting grids have that upgrade and it will work. I fixed this recently in efab 0.1.0 where it will always pick the best crafting grid for autocrafting

**Comment by Chaftalie** [comment]
Thank you for your fast response! Now I understand the autocrafting sStem a lot better 😅
