### ISSUE TITLE
custom recipe with thermal dynamics doesnt work

### ISSUE THREAD

**Issue by redgoblin88** [McJty/EFab#17]
i have been trying for a while now to make a custom thermal expansions duct recipe however for some reason it does not seem to like "thermaldynamics:duct_48" i assume because it doesnt like underscored item names as it was also throwing an error for "thermalfoundation:material:323" which i found that FTB continuum had that as metadata so i replicated below. 

[crash-2018-06-25_19.34.28-client.txt](https://github.com/McJtyMods/EFab/files/2134287/crash-2018-06-25_19.34.28-client.txt)

in the log it says "Expected name at line 14 column 53" in which the script pasted below is an exact copy of what i have got (well, instead of spaced out it is tabbed out with notepad++)

{
    "type": "shaped",
    "output":{"item": "thermaldynamics:duct_0*3"},
    "input":[
      "rar",
      "pdp",
      "rar"
    ],
    "inputmap": {
      "r":{"item": "minecraft:redstone"},
      "a":{"item": "enderio:item_alloy_ingot", "meta": 4},
      "p":{"item": "thermalfoundation:material", "meta": 323},
	  "d":{"item": "thermaldynamics:duct_48"},},
	,"time": 30, "tiers": ["GEARBOX"]}

**Comment by McJty** [comment]
This line is wrong:

"d":{"item": "thermaldynamics:duct_48"},},

Get rid of the two comma's at the end. Both are wrong
