### ISSUE TITLE
Item Storages Pulls Items from other Storages

### ISSUE THREAD

**Issue by ghost** [McJty/EFab#19]
Named Item Storages Pulls Items from other Storages.
This happens when both Storages are used currently by a crafter and the recipe contain same Items like Redstone.

End result of this is that for example a single Item like a Redstone is in the wrong Item Storage.

**Comment by Proha5** [comment]
I have same problem.
Impossible create big autocraft system. :(

**Comment by bothie** [comment]
Kinda sounds like the bug fixed on 30 Jun here: https://github.com/McJtyMods/EFab/commit/e13d93cf863b332aecabd381fab8653c4e2c1644

@McJty, please do a release with that bugfix, modpacks like FTB Continuum still ship the broken version.

**Comment by McJty** [comment]
I'll release today or tomorrow
