### ISSUE TITLE
Placing the crafting grid on a big multiblock causes lag spikes or a crash-loop

### ISSUE THREAD

**Issue by 016Nojr** [McJty/EFab#2]
On the ftbone server I have a big efab multiblock, the multiblock is located in Advanced Rocketry's space station dimension.

Forge: 14.23.3.2678
Efab: 0.0.36
McJtyLib: 2.6.7

It's a 21x21x1 layer of efab bases and 36 of them being rf storages, 9 elevator blocks (OpenBlocks) and one magma block for the boiler.
I have 19 Item Storages, 19 Crafters, 1 Boiler, 1 Steam Engine, 1 Power Optimizer, 1 Rf Control, 2 Pipes, 1 Processor, 1 Efab Crafting Grid, 4 Gearboxes and 9 tanks that each consists of 5 advanced tanks.

The gaps in the layer are supposed to be rf storages.

![2018-05-06_16 48 16](https://user-images.githubusercontent.com/8192699/39674510-54a5e42a-514d-11e8-882f-8078cbd266f2.png)

Now, when I try breaking/placing rf storages the server has a big lag spikes, sometimes enough to boot you off the server, and a couple times it crashed: [Crash log](https://pastebin.com/RTnX3hFy)

I first discovered this when placing the crafting grid, that's when the first spike happened, and it has happened since, when I removed this crafting grid, the lag spikes stopped happening. When I place it back, the lag spikes start when breaking or placing rf storages, or any other block except efab bases. Break it and the spikes are gone.

I placed it again, this time the server went into a crash loop: [Log](https://pastebin.com/vbWdwEQ8)

Information from Sampler about the block
![efab](https://user-images.githubusercontent.com/8192699/39706852-f69e9018-5212-11e8-9a78-537b98af5607.PNG)

Reproduced in singleplayer, Sampler (1.73) gave me this [Log](https://pastebin.com/LjamJecf)
In singleplayer I removed all "special" blocks and the levers powering the crafters, still stalling the game.

I think the issue here is how the efab crafting grid handles the calculating of the multiblock when first placed. However I think it's also related to how many block is placed in any direction of the crafting grid. The issue didnt happen when it was placed close to the middle, but as it was moved further towards the corners it increased the time it took to calculate the multiblock to the point the client couldnt handle it anymore and stalled the game.

**Comment by SeeTwoDev** [comment]
I have a similar issue... i was extending my setup to take all of my base's floor with exchangers. it then led to server crashes. 

at mcjty.efab.blocks.grid.GridTE.findMultiBlockParts(GridTE.java:792)
	at mcjty.efab.blocks.grid.GridTE.checkMultiBlockCache(GridTE.java:859)
	at mcjty.efab.blocks.grid.GridTE.updateCrafters(GridTE.java:230)
	at mcjty.efab.blocks.grid.GridTE.func_73660_a(GridTE.java:298)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

**Comment by McJty** [comment]
Is this still happening with the very latest version of efab?

**Comment by lglare** [comment]
i happen same issue on efab-0.1.0.
