### ISSUE TITLE
Efab still will not craft anything that requires RF

### ISSUE THREAD

**Issue by Solverbolt** [McJty/EFab#27]
Attempted to use every single suggestion on previous issue requests posted. None of them work. It makes a short circuit sound, then wont work. First it tried, made it to 20 seconds of crafting, before failing and stopping, and that was with plenty of power pumping into the system from a 10 Million RF storage. Was trying to craft the machine frame to progress.  So no, ITS NOT WORKING AS INTENDED.

**Comment by McJty** [comment]
Show me the tooltip of the 'start' button. Also describe your setup

**Comment by McJty** [comment]
FYI people are actually crafting with RF so it sure works. The modpack wouldn't work without this ability. We just have to find out what's different about your setup

**Comment by McJty** [comment]
Closing due to lack of response

**Comment by FavouriteDragon** [comment]
@Solverbolt Is just a troll- don't worry about this issue.
