### ISSUE TITLE
Support for NBT/Enchantments?

### ISSUE THREAD

**Issue by Vyraal1** [McJty/EFab#30]
Hi McJty,

Given the following json recipe, it seems to only output regular iron chestplates. We want to make it so that processing certain armors in the efab applies an enchantment to the armor (later on planning to make use of Armory Upgrade. Would it be possible if there could be a syntax that reads for NBT tags?

```json
  {
    "type": "shaped",
    "output": {
      "item": "minecraft:iron_chestplate",
      "ench": [
          {
            "lvl": 1,
            "id": 0
          }
        ]
    },
    "input": [
      "iii",
      "iri",
      "iii"
    ],
    "inputmap": {
      "r": {
        "item": "minecraft:iron_chestplate"
      },
      "i": {
        "item": "thermalfoundation:material:32",
        "meta": "32"
      }
    },
    "time": 30
  },```

**Comment by Vyraal1** [comment]
Another use case would allow EFab to directly manufacture specific Tinkers parts, which are identified via NBT as well, such as a Cobalt Hammer Head.

**Comment by Vyraal1** [comment]
So I was told that this exists: https://github.com/McJtyMods/EFab/blob/d94cf0a4c34b106eb8def618d4f0947141ba91c1/src/main/java/mcjty/efab/recipes/StandardRecipes.java#L224

and then changed my recipe to:
https://pastebin.com/BWtAiZXe

However, this resulted in a crash as shown here: https://paste.dimdev.org/rudamizura.mccrash

**Comment by McJty** [comment]
You should specify the nbt as a string containing json. i.e. something like:

"nbt": "{ \"ench\": [  {  \"lvl\": 1,  \"id\": 0  }   ]  }"

**Comment by Vyraal1** [comment]
Perfect, actually got it working after needing to escape it, thanks!
