### ISSUE TITLE
Pipes Don't Assign Ownership

### ISSUE THREAD

**Issue by Shananiganeer** [McJty/EFab#34]
PipeBlock overrides onBlockPlacedBy, but never calls super.onBlockPlacedBy so McJtyLib ownership is not set correctly and the EFab never recognizes any placed pipes.

**Comment by Shananiganeer** [comment]
This is still broken. Without the commit that I submitted, the EFab never recognizes any attached pipes.

**Comment by McJty** [comment]
I don't understand why this is an issue? EFab doesn't look at ownership when looking for attached pipes

**Comment by Shananiganeer** [comment]
Test it yourself. Without the commit I submitted the EFab doesn't run any faster with pipes attached.

I'll post a vid showing the difference in a day or two.

**Comment by McJty** [comment]
That must be for some other reason because this is the code that looks for adjacent pipes:

                } else if (block == ModBlocks.pipeBlock) {
                    pipes.add(p);

Later on pipes is only used to test if a position is in it. Nowhere is EFab testing for ownership as far as I can see (and remember coding). So before adding this I need to know what exactly causes this problem

**Comment by Shananiganeer** [comment]
Ok, give me a bit and I'll post a vid showing the issue. When I first ran into the issue and looked at the source code that seemed the most likely culprit (when you place pipes in-game their tooltip is broken and if you pick it back up it complains about ownership not being set correctly), but when you see it maybe you'll think of a different cause.
