### ISSUE TITLE
Error: java.lang.NoClassDefFoundError: Lmcjty/efab/proxy/CommonProxy;

### ISSUE THREAD

**Issue by bdog73** [McJty/EFab#39]
how do i  fix this

**Comment by McJty** [comment]
I already answered this. Just make sure all my mods are up to date

**Comment by bdog73** [comment]
it jest this mod it even happens when i jest use this mod and nonetheless install.

**Comment by bdog73** [comment]
jest fix it

**Comment by McJty** [comment]
I can't fix it. It is at your side. What versions of McJtyLib and EFab are you using?
