### ISSUE TITLE
EFab Crash

### ISSUE THREAD

**Issue by SjetCraft** [McJty/EFab#40]
Forge 14.23.5.2816 
EFab 0.2.0

Modpack: [Manufactio](https://www.curseforge.com/minecraft/modpacks/manufactio)

Crashing on completing the crafting of an item with EFab. Crash seems to occur when using multiple EFab Crafting Grids at the same time. Cannot replicate at will.

Crashlog: https://pastebin.com/gK5B50ML

Note: [similar issue](https://www.curseforge.com/minecraft/modpacks/manufactio/issues/8)

**Comment by McJty** [comment]
It is crashing in another mod:
    at com.suppergerrie2.sdrones.items.crafting.RecipeFilterDrone.shouldAddFilter(RecipeFilterDrone.java:67)
    at com.suppergerrie2.sdrones.items.crafting.RecipeFilterDrone.matches(RecipeFilterDrone.java:55)

Some mode with drones? Probably not related to EFab. Please report to them

**Comment by SjetCraft** [comment]
Thanks, sorry for the bother.
