### ISSUE TITLE
tools.

### ISSUE THREAD

**Issue by bdog73** [McJty/EFab#41]
cant craft tools and the upgrades have no crafting recipe.

**Comment by McJty** [comment]
Context? Info? Versions? Please give me a more accurate description and a LOT more detail

**Comment by bdog73** [comment]
0.2.0 works when i jest have the mod install alone but when i put it in my modded pack when i hit start when i am making a tool nothing happen,and when i click on the upgrade in jei there is no recipe.

**Comment by McJty** [comment]
What tool are you making? Please be more specific. I need exact concrete information on what you're trying to do

**Comment by bdog73** [comment]
i cant make all tools and weapons.

**Comment by bdog73** [comment]
and yes i have the upgrade install.

**Comment by McJty** [comment]
What recipes did you configure? By default does not come with any (useful) recipes

**Comment by bdog73** [comment]
i can make them in the vanilla not the efab crafting grid.

**Comment by McJty** [comment]
I really don't understand. Please give a CONCRETE example. An actual thing you are trying to make. Describe in full detail

**Comment by bdog73** [comment]
i am trying a bow to make dispenser and making a ax the ax is made of wood and a Crook from Ex Nihilo.

**Comment by McJty** [comment]
Trying a bow? What does that mean? Also in what are you trying to make this? Please show screenshots. Last chance. Otherwise I close this and recommend that you learn how to do proper bug reports

**Comment by bdog73** [comment]
![2019-11-18_09 43 51](https://user-images.githubusercontent.com/51036217/69061977-2f5e6700-09e8-11ea-826c-aebe042013ec.png)
click start and nothing happens.

**Comment by McJty** [comment]
Ok and is the bow a recipe that you configured? Also did you enable vanilla recipes in the EFab grid? Maybe you can show all your configs

**Comment by bdog73** [comment]
hear the # Configuration file

##########################################################################################################
# general
#--------------------------------------------------------------------------------------------------------#
# General settings
##########################################################################################################

general {
    # How much RF/t the advanced RF Storage block can contribute to crafting [range: 1 ~ 10000000, default: 100]
    I:advancedRfStorageInternalFlow=100

    # The maximum amount of RF for the advanced RF Storage block [range: 1 ~ 1000000000, default: 100000]
    I:advancedRfStorageMax=100000

    # The ambient temperature of the boiler when no heat is below it [range: 0.0 ~ 100.0, default: 20.0]
    S:ambientBoilerTemperature=20.0

    # The volume for the beeps sound (0.0 is off) [range: 0.0 ~ 1.0, default: 0.2]
    S:baseBeepsVolume=0.2

    # The volume for the machine sound (0.0 is off) [range: 0.0 ~ 1.0, default: 1.0]
    S:baseMachineVolume=1.0

    # The volume for the sparks sound (0.0 is off) [range: 0.0 ~ 1.0, default: 0.7]
    S:baseSparksVolume=0.7

    # The volume for the steam sound (0.0 is off) [range: 0.0 ~ 1.0, default: 1.0]
    S:baseSteamVolume=1.0

    # Every tick the boiler will cool down this amount if there is no source of heat below it [range: 0.0 ~ 100.0, default: 0.3]
    S:boilerCoolTemperature=0.3

    # Every tick the boiler will heat up this amount if there is a source of heat below it [range: 0.0 ~ 100.0, default: 0.5]
    S:boilerRiseTemperature=0.5

    # Number of ticks that the animation of the crafter will speed up during auto crafting [range: 1 ~ 100000, default: 40]
    I:craftAnimationBoost=40

    # Every tick the animation of the crafter will speed up during auto crafting (and during boost) [range: 0.0 ~ 1000.0, default: 3.0]
    S:craftAnimationSpeedUp=3.0

    # If not auto crafting this is the speed at which the speed of the animation of the crafter will decrease [range: 0.0 ~ 1000.0, default: 0.3]
    S:craftAnimationSpinDown=0.3

    # Number of ticks between every auto craft operation [range: 1 ~ 100000, default: 10]
    I:crafterDelay=10

    # Number of ticks that the rotating spheres will speed up during mana crafting [range: 1 ~ 100000, default: 40]
    I:manaRotationBoost=40

    # Every tick the rotating spheres will speed up during mana crafting (and during boost) [range: 0.0 ~ 1000.0, default: 2.0]
    S:manaRotationSpeedUp=2.0

    # If not mana crafting this is the speed at which the speed of the rotating spheres will decrease [range: 0.0 ~ 1000.0, default: 0.3]
    S:manaRotationSpinDown=0.3

    # The maximum temperature for the boiler (it generates steam over 100C) [range: 100.0 ~ 1000.0, default: 200.0]
    S:maxBoilerTemperature=200.0

    # Maximum speed factor for the animation of the crafter during auto crafting [range: 1.0 ~ 1000.0, default: 20.0]
    S:maxCraftAnimationSpeed=20.0

    # Maximum amount of mana that can be stored in the mana receptacle [range: 1 ~ 100000000, default: 10000]
    I:maxMana=10000

    # Maximum speed factor for the rotating spheres of the mana receptacle during mana crafting [range: 1.0 ~ 1000.0, default: 20.0]
    S:maxManaRotationSpeed=20.0

    # Maximum amount of mana that can be used per tick per mana receptacle [range: 1 ~ 10000000, default: 1000]
    I:maxManaUsage=1000

    # The maximum speed bonus on a liquid crafting operation [range: 1 ~ 64, default: 2]
    I:maxPipeSpeedBonus=2

    # The maximum speed bonus on a crafting operation you can get by adding multiple machine parts [range: 1 ~ 64, default: 4]
    I:maxSpeedupBonus=4

    # Maximum speed factor for the spinning wheel of the stean engine during steam crafting [range: 1.0 ~ 1000.0, default: 20.0]
    S:maxSteamWheelSpeed=20.0

    # How much RF/t the RF Control block can receive [range: 1 ~ 10000000, default: 10]
    I:rfControlInputPerTick=10

    # The maximum amount of RF for the RF Control block [range: 1 ~ 100000000, default: 20]
    I:rfControlMax=20

    # How much RF/t the RF Storage block can receive [range: 1 ~ 10000000, default: 50]
    I:rfStorageInputPerTick=50

    # How much RF/t the RF Storage block can contribute to crafting [range: 1 ~ 10000000, default: 30]
    I:rfStorageInternalFlow=30

    # The maximum amount of RF for the RF Storage block [range: 1 ~ 100000000, default: 10000]
    I:rfStorageMax=10000

    # Amount of ticks that the beeps sound should play [range: 0 ~ 1000000, default: 8]
    I:soundBeepsTicks=8

    # Amount of ticks that the gearbox sound should play [range: 0 ~ 1000000, default: 50]
    I:soundMachineTicks=50

    # Amount of ticks that the sparks sound should play [range: 0 ~ 1000000, default: 25]
    I:soundSparksTicks=25

    # Amount of ticks that the steam sound should play [range: 0 ~ 1000000, default: 50]
    I:soundSteamTicks=50

    # Number of ticks that the steam wheel will speed up during steam crafting [range: 1 ~ 100000, default: 40]
    I:steamWheelBoost=40

    # Every tick the steam wheel will speed up during steam crafting (and during boost) [range: 0.0 ~ 1000.0, default: 2.0]
    S:steamWheelSpeedUp=2.0

    # If not steam crafting this is the speed at which the speed of the wheel will decrease [range: 0.0 ~ 1000.0, default: 0.3]
    S:steamWheelSpinDown=0.3

    # Capacity of each tank (tier 2) block in MB [range: 1 ~ 1000000, default: 64000]
    I:tank2Capacity=64000

    # Capacity of each tank block in MB [range: 1 ~ 1000000, default: 16000]
    I:tankCapacity=16000

    # If -1 then the efab will pause the crafting until mana is available. Otherwise it will allow a delay of the specified amount of ticks before aborting [range: -1 ~ 1000000000, default: 1]
    I:ticksAllowedWithoutMana=1

    # If -1 then the efab will pause the crafting until power is available. Otherwise it will allow a delay of the specified amount of ticks before aborting [range: -1 ~ 1000000000, default: 1]
    I:ticksAllowedWithoutRF=1

    # The amount of time needed for the grid/crafter to craft normal vanilla recipes [range: 0 ~ 1000000, default: 1]
    I:vanillaCraftTime=1

    # If enabled the EFab grid and crafter will also support vanilla recipes. If disabled they don't [default: true]
    B:vanillaCraftingAllowed=true

    # Amount of water per tick that is being consumed during a steam crafting operation [range: 0 ~ 1000000, default: 5]
    I:waterSteamCraftingConsumption=5

    # Amount of water that is needed to be able to start a steam crafting operation [range: 0 ~ 1000000, default: 500]
    I:waterSteamStartAmount=500
}

**Comment by McJty** [comment]
Hmm no idea. Seems that should work. What about other recipes?

**Comment by bdog73** [comment]
the other recipes work find.

**Comment by bdog73** [comment]
got it it is astral sorcery that is confining with the mod.
