### ISSUE TITLE
im no expert but i think efab is throwing errors????

### ISSUE THREAD

**Issue by reapersremorse** [McJty/EFab#7]
i know this may not need to go to you but i figure it would be faster than ftb trying to contact you.
also i posted this to the ftb teams issue tracker first.

**Modpack ftb continuum Version 1.0.2

**Issue honestly dont know, crashes randomly
related to efab (im no coder and im an idiot so when reading the files i couldn't figure it out)

**Link to Log or Crash File Paste
main/last was the direct copy of what i saw right when i crashed in the video if that helps.

main/ last log: https://paste.feed-the-beast.com/view/5bad566d
old: https://paste.feed-the-beast.com/view/35cf00f4
old: https://paste.feed-the-beast.com/view/b80ed83c

most logs were deleted, the crash happened around 6 or 7 times before the one in the video.

Is it Repeatable?: kinda.... watch video https://youtu.be/Q0qfg9ZFpV4
video may take a bit to be completely uploaded, youtube likes to take their time.

thank you for your time and sorry for my crap typing and spelling skills...

**Comment by McJty** [comment]
Seems you're having issues with java crashing. Not related to efab

**Comment by reapersremorse** [comment]
thanks, ill look into it. sorry for bothering you.
