### ISSUE TITLE
[Question/Plea] Having problems crafting the machine frame in FTB Continuum

### ISSUE THREAD

**Issue by togreglove** [McJty/EFab#9]
I try to craft the machine frame and it makes an electic buzzing sound for a second, then stops.
There are no errors listed on the Start button, and my abilities far exceed what is listed as necessary.
When I hit Start, the timer appears above the start button and immediately disappears again.
I have double checked the ingredients in the table, have plenty of the liquid ingredients.
All blocks are connected properly.
I tried re-arranging blocks to see if that mattered. 
All energy related blocks have power flowing directly to them and have full power indicators.

I'm at a loss, and am stuck.

Any ideas?

**Comment by togreglove** [comment]
Relevant Screenshot
![image](https://user-images.githubusercontent.com/20768427/40691559-3802a588-6372-11e8-8287-e9a218449e07.png)

**Comment by togreglove** [comment]
Update: Scaling back to 1 RF Control made it work. Still, not closing it because it *should* have worked.

**Comment by Degenerecy** [comment]
Continuum Pack: 1.1.0
EFab ver: 0.0.36
~~I have same issue with Electronic Circuit.  The Info says 1k rf/t, I have 5 RF Storage modules and 4 Rf Controls, and cant craft.  I have tried reducing it to 1 Rf Controller but no luck.  

Originally thought it was my setup but the system does craft servo's(50 rf/t craft).  Might be a pack issue.~~

**_Edit/Update:  Fix/Working as intended.  From the Continuum pack bug section, the gearbox's and Rf controls add to the power requirement.  Reducing them to 1 each changes the power requirement to the default recipe cost._**

**Comment by McJty** [comment]
Yes working as intended

**Comment by Degenerecy** [comment]
Thx, I couldn't find it in any documentation or spotlights that say it adds to the power requirement.

**Comment by McJty** [comment]
Well it actually doesn't.  The total power needed for the recipe is constant.  So it only makes sense that the rf/t goes up if the craft speed goes up (because the recipe is sped up by multiple gear boxes for example). Note that de tooltip on the grid craft button actually gives the adjusted rf/t

**Comment by Degenerecy** [comment]
Yea, noticed it after i found my error.  Side note:  While the crafting failed to start, it did however consume the rf to make(in continuum, its 100k for 1.   Not really a problem but more of an observation in case its not intended to consume rf on a failure to start.(unsure if it consumed 100k, just noticed my fluxducts lost their buffer every click.)

**Comment by Bizuex** [comment]
I was having the same issue. If you have 2 RF controlers you may be scalling up the recipe (you can check that hoving the mouse over the START button). I had to scale down by having only one RF controler.

**Comment by TheFrostSeraph** [comment]
Hey guys, ive been having the same problem. I also had it on REther Pearls, but apparently changing to 1 rf control worked, still, for the machine frames, no matter what my gearbox rf control combination is, I get the bug over and over, it starts and suddenly stops, conuming the rf.
Anyone can help?

**Comment by McJty** [comment]
If you add more rf controls it will consume more RF/t. That's *not* a bug. The reason is that it goes faster. And the total amount of power has to remain the same. So if you craft at double the speed then obviously you will consume double the amount of RF/t. Make sure you feed in enough RF and that every RF control has RF in it

**Comment by TheFrostSeraph** [comment]
Thank you, apparently, it was just that since i got it 2 times faster (dont know why thofuh cause only 1 gear box and 1 control) i was getting more RF/t of what i actually had with the efab stuff.

**Comment by Solverbolt** [comment]
The current configuration wont allow for the machine frame to be crafted with anything less than double speed, because of the requirement of 400rf/tick which is putting it up to 2x. So again, as my new issue opened states, it is NOT working as intended

**Comment by Galeban** [comment]
Sorry to bump an old post on this but I thought I would weigh in since I just ran into this issue on my own pack.  The issue I ran into with this craft is that it takes speed modifiers from several different parts of Efab (gears, pipes, controllers).  When I attempted to run this craft on my Efab I know I had plenty rf/t because I had installed 2 storage cells into the efab each contributing 250 rf/t but when I went to craft it the rf/t requirement was much higher than it showed in the JEI.  Turns out even the pipes speed up (because of coarse it has a liquid component) added to the rf/t when I went to craft.  I just removed some speed upgrades off and I was good to go.

**Comment by dws14159** [comment]
Same problem here - in my case the solution was to add more liquid steel.  Although I had and needed exactly 1296mB, it wouldn't go without an extra ingot chucked in.  So there's probably an "if moltenSteel > 1296" instead of >= in there.
